openapi: 3.0.0
info:
  title: Stability Protocol Free Transactions API
  description: API for interacting with Stability Protocol's free transactions service.
  version: "1.0.0"
  contact:
    name: API Support
    url: https://stabilityprotocol.com/support
    email: support@stabilityprotocol.com
servers:
  - url: https://api.stabilityprotocol.com/v1
    description: Stability Protocol API base URL
paths:
  /free-transactions/{address}:
    get:
      summary: Retrieve free transactions for a specific address
      operationId: getFreeTransactions
      tags:
        - Transactions
      parameters:
        - name: address
          in: path
          required: true
          description: Ethereum address to retrieve the transactions for
          schema:
            type: string
            pattern: "^0x[a-fA-F0-9]{40}$"
      responses:
        "200":
          description: A list of free transactions for the given address
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Transaction"
                  remaining:
                    type: number
        "400":
          description: Bad request, e.g., if the address is not in the correct format
        "404":
          description: Address not found
        "500":
          description: Internal server error

  paid-transactions/keys:
    get:
      summary: Retrieve api key details
      operationId: getApiKeyDetails
      tags:
        - Paid Transactions
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: Bearer ${SupabaseAuthToken}
          required: true
      responses:
        "200":
          description: Success Retrieving Information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiKey"

    post:
      summary: Create api key
      operationId: createApiKey
      tags:
        - Paid Transactions
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: Bearer ${SupabaseAuthToken}
          required: true
      responses:
        "200":
          description: Success creating info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiKey"

components:
  schemas:
    Transaction:
      type: object
      properties:
        txHash:
          type: string
          description: The transaction hash
        blockNumber:
          type: integer
          format: int64
          description: The block number in which the transaction was recorded
        from:
          type: string
          description: The initiating transaction address
        to:
          type: string
          description: The receiving transaction address
        value:
          type: string
          description: The value transferred in the transaction
        gasUsed:
          type: integer
          format: int64
          description: The amount of gas used for the transaction
        timestamp:
          type: string
          format: date-time
          description: The timestamp for when the transaction was included in the block
    ApiKey:
      type: object
      properties:
        api_key:
          type: string
        email:
          type: string
        created_at:
          type: string
        granularity:
          type: string
          enum: ["day", "month", "year", "prepaid"]
        enabled:
          type: boolean
